name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build
      - name: Test
        run: pnpm run test
      - name: Deploy to server via SSH
        if: success() && github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.BACKEND_APP_PATH }}
            git pull origin main
            make runapp
    # Always run this step to notify Discord if the job failed
    - name: Notify Discord on failure (any step)
      if: failure()
      uses: Ilshidur/action-discord@master
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: |
          ❌ Backend CI/CD FAILED on ${{ github.repository }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          Workflow: ${{ github.workflow }}
          <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>
    - name: Notify Discord on success
      if: success()
      uses: Ilshidur/action-discord@master
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: |
          ✅ Backend CI/CD SUCCESS on ${{ github.repository }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          Workflow: ${{ github.workflow }}
          <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}> 